var a=10;
var l=5;
var b=15;
var h=80;
var t=6*a*a;
var v=a*a*a;
var y=4*(l+b+h);
console.log("Total surface area of a cube:"+t);
console.log("Volume of a cube:"+v);
console.log("Perimeter of a cube:"+y);
